In [100]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [101]:
data1 = pd.read_csv('energy_data.csv')
data1.head(5)

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  11/01/2016 17:00          60      30  19.89  47.596667  19.2  44.790000   
1  11/01/2016 17:10          60      30  19.89  46.693333  19.2  44.722500   
2  11/01/2016 17:20          50      30  19.89  46.300000  19.2  44.626667   
3  11/01/2016 17:30          50      40  19.89  46.066667  19.2  44.590000   
4  11/01/2016 17:40          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9  T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53   6.60        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56   6.48        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50   6.37        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40   6.25        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40   6.13        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410390  45.410390  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [102]:
data1 = data1.drop('date', axis = 1)
data1.head()

Appliances  lights     T1       RH_1    T2       RH_2     T3       RH_3  \
0          60      30  19.89  47.596667  19.2  44.790000  19.79  44.730000   
1          60      30  19.89  46.693333  19.2  44.722500  19.79  44.790000   
2          50      30  19.89  46.300000  19.2  44.626667  19.79  44.933333   
3          50      40  19.89  46.066667  19.2  44.590000  19.79  45.000000   
4          60      40  19.89  46.333333  19.2  44.530000  19.79  45.000000   

          T4       RH_4  ...         T9   RH_9  T_out  Press_mm_hg  RH_out  \
0  19.000000  45.566667  ...  17.033333  45.53   6.60        733.5    92.0   
1  19.000000  45.992500  ...  17.066667  45.56   6.48        733.6    92.0   
2  18.926667  45.890000  ...  17.000000  45.50   6.37        733.7    92.0   
3  18.890000  45.723333  ...  17.000000  45.40   6.25        733.8    92.0   
4  18.890000  45.530000  ...  17.000000  45.40   6.13        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410390  45.410390  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 28 columns]

In [103]:
#RENAME COLUMNS

columns = {
    'T1' : 'T1-TEMP IN KITCHEN ^C',
    'RH_1' : 'RH_1-HUMIDITY IN KITCHEN %',
    'T2' : 'T2-TEMP IN LIVING_ROOM ^C',
    'RH_2' : 'RH_2-HUMIDITY IN LIVING_ROOM %',
    'T3' : 'T3-TEMP IN LAUNDRY_ROOM ^C',
    'RH_3' : 'RH_3-HUMIDITY IN LAUNDRY_ROOM %',
    'T4' : 'T4-TEMP IN OFFICE_ROOM ^C',
    'RH_4' : 'RH_4-HUMIDITY IN OFFICE_ROOM %',
    'T5' : 'T5-TEMP IN BATHROOM ^C',
    'RH_5' : 'RH_5-HUMIDITY IN BATHROOM %',
    'T6' : 'T6-TEMP OUTSIDE_NORTH ^C',
    'RH_6' : 'RH_6-HUMIDITY IN OUTSIDE_NORTH %',
    'T7' : 'T7-TEMP IN IRONING_ROOM ^C',
    'RH_7' : 'RH_7-HUMIDITY IN IRONING_ROOM %',
    'T8' : 'T8-TEMP IN TEEN_ROOM ^C',
    'RH_8' : 'RH_8-HUMIDITY IN TEEN_ROOM %',
    'T9' : 'T9-TEMP IN MASTER_ROOM ^C',
    'RH_9' : 'RH_9-HUMIDITY IN MASTER_ROOM %',
    'T_out' : 'T_out-TEMP OUTSIDE_WEATHER STATION ^C',
    'RH_out' : 'RH_out-HUMIDITY OUTSIDE_WEATHER STATION %',
    'Press_mm_hg' : 'Press_mm_hg-PRESSURE_STATION mmHg',
    'Windspeed' : 'WS-WEATHER STATION m/s',
    'Visibility' : 'Visibility-WEATHER STATION km',
    'Tdewpoint' : 'TDP-WEATHER STATION A^C',
    'rv1' : 'rv1-RANDOM VARIABLE1',
    'rv2' : 'rv2-RANDOM VARIABLE2',
}

data1 = data1.rename(columns = columns)
data1.head(2)

Appliances  lights  T1-TEMP IN KITCHEN ^C  RH_1-HUMIDITY IN KITCHEN %  \
0          60      30                  19.89                   47.596667   
1          60      30                  19.89                   46.693333   

   T2-TEMP IN LIVING_ROOM ^C  RH_2-HUMIDITY IN LIVING_ROOM %  \
0                       19.2                         44.7900   
1                       19.2                         44.7225   

   T3-TEMP IN LAUNDRY_ROOM ^C  RH_3-HUMIDITY IN LAUNDRY_ROOM %  \
0                       19.79                            44.73   
1                       19.79                            44.79   

   T4-TEMP IN OFFICE_ROOM ^C  RH_4-HUMIDITY IN OFFICE_ROOM %  ...  \
0                       19.0                       45.566667  ...   
1                       19.0                       45.992500  ...   

   T9-TEMP IN MASTER_ROOM ^C  RH_9-HUMIDITY IN MASTER_ROOM %  \
0                  17.033333                           45.53   
1                  17.066667                           45.56   

   T_out-TEMP OUTSIDE_WEATHER STATION ^C  Press_mm_hg-PRESSURE_STATION mmHg  \
0                                   6.60                              733.5   
1                                   6.48                              733.6   

   RH_out-HUMIDITY OUTSIDE_WEATHER STATION %  WS-WEATHER STATION m/s  \
0                                       92.0                7.000000   
1                                       92.0                6.666667   

   Visibility-WEATHER STATION km  TDP-WEATHER STATION A^C  \
0                      63.000000                      5.3   
1                      59.166667                      5.2   

   rv1-RANDOM VARIABLE1  rv2-RANDOM VARIABLE2  
0             13.275433             13.275433  
1             18.606195             18.606195  

[2 rows x 28 columns]

In [104]:
data1.isnull().sum()

Appliances                                   0
lights                                       0
T1-TEMP IN KITCHEN ^C                        0
RH_1-HUMIDITY IN KITCHEN %                   0
T2-TEMP IN LIVING_ROOM ^C                    0
RH_2-HUMIDITY IN LIVING_ROOM %               0
T3-TEMP IN LAUNDRY_ROOM ^C                   0
RH_3-HUMIDITY IN LAUNDRY_ROOM %              0
T4-TEMP IN OFFICE_ROOM ^C                    0
RH_4-HUMIDITY IN OFFICE_ROOM %               0
T5-TEMP IN BATHROOM ^C                       0
RH_5-HUMIDITY IN BATHROOM %                  0
T6-TEMP OUTSIDE_NORTH ^C                     0
RH_6-HUMIDITY IN OUTSIDE_NORTH %             0
T7-TEMP IN IRONING_ROOM ^C                   0
RH_7-HUMIDITY IN IRONING_ROOM %              0
T8-TEMP IN TEEN_ROOM ^C                      0
RH_8-HUMIDITY IN TEEN_ROOM %                 0
T9-TEMP IN MASTER_ROOM ^C                    0
RH_9-HUMIDITY IN MASTER_ROOM %               0
T_out-TEMP OUTSIDE_WEATHER STATION ^C        0
Press_mm_hg-P

# QUESTION 12

In [110]:

#NORMALIZE DATASET USING MIN-MAX SCALER

scaler = MinMaxScaler ()
normalized_data1 = pd.DataFrame(scaler.fit_transform(data1), columns = data1.columns)
features_data1 = normalized_data1['T2-TEMP IN LIVING_ROOM ^C'].values.reshape(-1, 1)

target = normalized_data1['T6-TEMP OUTSIDE_NORTH ^C']

In [111]:
#split dataset

X_train, X_test, y_train, y_test = train_test_split(features_data1, target, test_size = 0.3, random_state = 1)

In [112]:
#TRAIN DATASET

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [113]:
#TEST TRAINED MODEL

predict = model.predict(X_test)
predict

array([0.27457749, 0.44635267, 0.59807124, ..., 0.35286298, 0.45206773,
       0.39168223])

In [114]:
#CHECK PERFORMANCE USING R-SQUARED

r2 = r2_score(y_test, predict)
round(r2, 2)

0.65

# QUESTION 13

In [116]:
#already dropped data column in beginning

data13 = data1.drop('lights', axis = 1)
data13.head()

Appliances  T1-TEMP IN KITCHEN ^C  RH_1-HUMIDITY IN KITCHEN %  \
0          60                  19.89                   47.596667   
1          60                  19.89                   46.693333   
2          50                  19.89                   46.300000   
3          50                  19.89                   46.066667   
4          60                  19.89                   46.333333   

   T2-TEMP IN LIVING_ROOM ^C  RH_2-HUMIDITY IN LIVING_ROOM %  \
0                       19.2                       44.790000   
1                       19.2                       44.722500   
2                       19.2                       44.626667   
3                       19.2                       44.590000   
4                       19.2                       44.530000   

   T3-TEMP IN LAUNDRY_ROOM ^C  RH_3-HUMIDITY IN LAUNDRY_ROOM %  \
0                       19.79                        44.730000   
1                       19.79                        44.790000   
2                       19.79                        44.933333   
3                       19.79                        45.000000   
4                       19.79                        45.000000   

   T4-TEMP IN OFFICE_ROOM ^C  RH_4-HUMIDITY IN OFFICE_ROOM %  \
0                  19.000000                       45.566667   
1                  19.000000                       45.992500   
2                  18.926667                       45.890000   
3                  18.890000                       45.723333   
4                  18.890000                       45.530000   

   T5-TEMP IN BATHROOM ^C  ...  T9-TEMP IN MASTER_ROOM ^C  \
0               17.166667  ...                  17.033333   
1               17.166667  ...                  17.066667   
2               17.166667  ...                  17.000000   
3               17.166667  ...                  17.000000   
4               17.200000  ...                  17.000000   

   RH_9-HUMIDITY IN MASTER_ROOM %  T_out-TEMP OUTSIDE_WEATHER STATION ^C  \
0                           45.53                                   6.60   
1                           45.56                                   6.48   
2                           45.50                                   6.37   
3                           45.40                                   6.25   
4                           45.40                                   6.13   

   Press_mm_hg-PRESSURE_STATION mmHg  \
0                              733.5   
1                              733.6   
2                              733.7   
3                              733.8   
4                              733.9   

   RH_out-HUMIDITY OUTSIDE_WEATHER STATION %  WS-WEATHER STATION m/s  \
0                                       92.0                7.000000   
1                                       92.0                6.666667   
2                                       92.0                6.333333   
3                                       92.0                6.000000   
4                                       92.0                5.666667   

   Visibility-WEATHER STATION km  TDP-WEATHER STATION A^C  \
0                      63.000000                      5.3   
1                      59.166667                      5.2   
2                      55.333333                      5.1   
3                      51.500000                      5.0   
4                      47.666667                      4.9   

   rv1-RANDOM VARIABLE1  rv2-RANDOM VARIABLE2  
0             13.275433             13.275433  
1             18.606195             18.606195  
2             28.642668             28.642668  
3             45.410390             45.410390  
4             10.084097             10.084097  

[5 rows x 27 columns]

In [117]:
#NORMALIZE DATASET USING MIN-MAX SCALER

scaler = MinMaxScaler ()
normalized_data13 = pd.DataFrame(scaler.fit_transform(data13), columns = data13.columns)
features = normalized_data13[['T1-TEMP IN KITCHEN ^C', 'RH_1-HUMIDITY IN KITCHEN %', 'T2-TEMP IN LIVING_ROOM ^C',
                                       'RH_2-HUMIDITY IN LIVING_ROOM %', 'T3-TEMP IN LAUNDRY_ROOM ^C', 'RH_3-HUMIDITY IN LAUNDRY_ROOM %',
                                       'T4-TEMP IN OFFICE_ROOM ^C', 'RH_4-HUMIDITY IN OFFICE_ROOM %', 'T5-TEMP IN BATHROOM ^C',
                                       'RH_5-HUMIDITY IN BATHROOM %', 'T6-TEMP OUTSIDE_NORTH ^C', 'RH_6-HUMIDITY IN OUTSIDE_NORTH %',
                                       'T7-TEMP IN IRONING_ROOM ^C', 'RH_7-HUMIDITY IN IRONING_ROOM %', 'T8-TEMP IN TEEN_ROOM ^C',
                                       'RH_8-HUMIDITY IN TEEN_ROOM %', 'T9-TEMP IN MASTER_ROOM ^C', 'RH_9-HUMIDITY IN MASTER_ROOM %',
                                       'T_out-TEMP OUTSIDE_WEATHER STATION ^C', 'RH_out-HUMIDITY OUTSIDE_WEATHER STATION %', 'Press_mm_hg-PRESSURE_STATION mmHg',
                                       'WS-WEATHER STATION m/s', 'Visibility-WEATHER STATION km', 'TDP-WEATHER STATION A^C', 'rv1-RANDOM VARIABLE1',
                                       'rv2-RANDOM VARIABLE2']]

output = normalized_data13['Appliances']

In [118]:
#SPLIT DATASET

X, x, Y, y = train_test_split(features, output, test_size = 0.3, random_state = 42)

In [119]:
#TRAIN DATASET

model = LinearRegression()

model.fit(X, Y)

LinearRegression()

In [120]:
#TEST TRAINED MODEL

prediction = model.predict(x)
prediction

array([0.03319482, 0.24412217, 0.0340092 , ..., 0.06843864, 0.09999407,
       0.05760656])

In [124]:
#CHECK PERFORMANCE USING MEAN ABSOLUTE ERROR METRIC

mae = mean_absolute_error (y, prediction)
round(mae, 3)

0.05

# QUESTION 14

In [125]:
#CHECK PERFORMANCE USING RESIDUAL SUM OF SQUARES

rss = np.sqrt(mean_squared_error(y, prediction))
round(rss, 2)

0.09

# QUESTION 15

In [126]:
#CHECK PERFORMANCE USING MEAN SQUARED ERROR

rmse = mean_squared_error (y, prediction)
round(rmse, 3)

0.008

# QUESTION 16

In [127]:
#CHECK PERFORMANCE USING R-SQUARED

r2 = r2_score(y, prediction)
round(r2, 2)

0.15

# QUESTION 18

In [128]:
#APPLYING RIDGE OR L2 REGULARIZATION

l2_reg = Ridge(alpha = 0.4)
l2_reg.fit(X, Y)

Ridge(alpha=0.4)

In [129]:
prediction1 = l2_reg.predict(x)
prediction1

array([0.0331965 , 0.24044278, 0.03462127, ..., 0.06871992, 0.09998794,
       0.05882301])

In [130]:
rmse = mean_squared_error (y, prediction1)
round(rmse, 3)

0.008

In [131]:
#APPLYING LASSO OR L1 REGULARIZATION

l1_reg = Lasso(alpha = 0.001)
l1_reg.fit(X, Y)

Lasso(alpha=0.001)

# QUESTION 19

In [132]:
def weights_data1 (model, feat, column_name):
    
    #this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', column_name]
    weights_df[column_name].round(3)
    return weights_df

In [134]:
model_weights = weights_data1(model, X, 'Linear Model Weights')
l2_weights = weights_data1(l2_reg, X, 'L2 Weights')
l1_weights = weights_data1(l1_reg, X, 'L1 Weights')

In [135]:
final_weights = pd.merge(model_weights, l2_weights, on = 'Features')
final_weights = pd.merge(final_weights, l1_weights, on = 'Features')

print(final_weights)

                                     Features  Linear Model Weights  \
0              RH_2-HUMIDITY IN LIVING_ROOM %             -0.456662   
1       T_out-TEMP OUTSIDE_WEATHER STATION ^C             -0.321969   
2                   T2-TEMP IN LIVING_ROOM ^C             -0.236198   
3                   T9-TEMP IN MASTER_ROOM ^C             -0.189977   
4                RH_8-HUMIDITY IN TEEN_ROOM %             -0.157585   
5   RH_out-HUMIDITY OUTSIDE_WEATHER STATION %             -0.077748   
6             RH_7-HUMIDITY IN IRONING_ROOM %             -0.044620   
7              RH_9-HUMIDITY IN MASTER_ROOM %             -0.039808   
8                      T5-TEMP IN BATHROOM ^C             -0.015645   
9                       T1-TEMP IN KITCHEN ^C             -0.003242   
10                       rv2-RANDOM VARIABLE2              0.000765   
11                       rv1-RANDOM VARIABLE1              0.000765   
12          Press_mm_hg-PRESSURE_STATION mmHg              0.006832   
13    

# QUESTION 20

In [136]:
prediction2 = l1_reg.predict(x)
prediction2

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [139]:
#CHECK PERFORMANCE USING MEAN SQUARED ERROR

rmse = mean_squared_error (y, prediction2)
round(rmse, 3)

0.009